DROP TABLE IF EXISTS posts;

CREATE TABLE houses (
    id INTEGER PRIMARY KEY,
    CRIM FLOAT,
    ZN FLOAT,
    INDUS FLOAT,
    CHAS INT,
    NOX FLOAT,
    RM FLOAT,
    AGE FLOAT,
    DIS FLOAT,
    RAD FLOAT,
    TAX FLOAT,
    PTRATION FLOAT,
    B FLOAT,
    LSTAT FLOAT,
    MEDV FLOAT
);